package com.david.curator.util

object Constants {
  val APP_NAME = "Curator"

  val ENRICH_TOPIC = "enrich_trip"
  val CURATOR_TOPIC = "curator"
  val BOOTSTRAP_SERVERS = "localhost:9092"
  val SCHEMA_REGISTRY_URL = "http://localhost:8081"

  val STREAMING_INTERVAL = 1

  val ENRICH_CSV_FILE_STREAMING = "hdfs://localhost:9000/user/vagrant/bixi/gbfs/csv/enrich/streaming/";
  val CURATE_START_STATION_STATUS = "hdfs://localhost:9000/user/vagrant/bixi/gbfs/csv/curate/start_station_status/"
  val CURATE_END_STATION_STATUS = "hdfs://localhost:9000/user/vagrant/bixi/gbfs/csv/curate/end_station_status/"

  val DELIMITER = ";"

  val STATION_STATUS_COLUMN_STATION_ID = "station_id"
  val STATION_STATUS_COLUMN_NUM_BIKES_AVAILABLE = "num_bikes_available"
  val STATION_STATUS_COLUMN_NUM_EBIKES_AVAILABLE = "num_ebikes_available"
  val STATION_STATUS_COLUMN_NUM_BIKES_DISABLED = "num_bikes_disabled"
  val STATION_STATUS_COLUMN_NUM_DOCKS_AVAILABLE = "num_docks_available"
  val STATION_STATUS_COLUMN_NUM_DOCKS_DISABLED = "num_docks_disabled"
  val STATION_STATUS_COLUMN_IS_INSTALLED = "is_installed"
  val STATION_STATUS_COLUMN_IS_RENTING = "is_renting"
  val STATION_STATUS_COLUMN_IS_RETURNING = "is_returning"
  val STATION_STATUS_COLUMN_LAST_REPORTED = "last_reported"
  val STATION_STATUS_COLUMN_EIGHTD_HAS_AVAILABLE_KEYS = "eightd_has_available_keys"

  val ENRICH_COLUMN_START_DATE = "start_date"
  val ENRICH_COLUMN_START_STATION_CODE = "start_station_code"
  val ENRICH_COLUMN_START_STATION_ID = "start_station_id"
  val ENRICH_COLUMN_START_EXTERNAL_ID = "start_external_id"
  val ENRICH_COLUMN_START_NAME = "start_name"
  val ENRICH_COLUMN_START_SHORT_NAME = "start_short_name"
  val ENRICH_COLUMN_START_LAT = "start_lat"
  val ENRICH_COLUMN_START_LON = "start_lon"
  val ENRICH_COLUMN_START_RENTAL_METHODS0 = "start_rental_methods0"
  val ENRICH_COLUMN_START_RENTAL_METHODS1 = "start_rental_methods1"
  val ENRICH_COLUMN_START_CAPACITY = "start_capacity"
  val ENRICH_COLUMN_START_EIGHTD_HAS_KEY_DISPENSER = "start_eightd_has_key_dispenser"
  val ENRICH_COLUMN_START_HAS_KIOSK = "start_has_kiosk"
  val ENRICH_COLUMN_START_GOOGLE_API_GEOCODING_JSON = "start_google_api_geocoding_json"
  val ENRICH_COLUMN_END_DATE = "end_date"
  val ENRICH_COLUMN_END_STATION_CODE = "end_station_code"
  val ENRICH_COLUMN_END_STATION_ID = "end_station_id"
  val ENRICH_COLUMN_END_EXTERNAL_ID = "end_external_id"
  val ENRICH_COLUMN_END_NAME = "end_name"
  val ENRICH_COLUMN_END_SHORT_NAME = "end_short_name"
  val ENRICH_COLUMN_END_LAT = "end_lat"
  val ENRICH_COLUMN_END_LON = "end_lon"
  val ENRICH_COLUMN_END_RENTAL_METHODS0 = "end_rental_methods0"
  val ENRICH_COLUMN_END_RENTAL_METHODS1 = "end_rental_methods1"
  val ENRICH_COLUMN_END_CAPACITY = "end_capacity"
  val ENRICH_COLUMN_END_EIGHTD_HAS_KEY_DISPENSER = "end_eightd_has_key_dispenser"
  val ENRICH_COLUMN_END_HAS_KIOSK = "end_has_kiosk"
  val ENRICH_COLUMN_END_GOOGLE_API_GEOCODING_JSON = "end_google_api_geocoding_json"
  val ENRICH_COLUMN_DURATION_SEC = "duration_sec"
  val ENRICH_COLUMN_IS_MEMEMBER = "is_memember"

  val ENRICH_CSV_SCHEMA = ENRICH_COLUMN_START_DATE + DELIMITER +
    ENRICH_COLUMN_START_STATION_CODE + DELIMITER +
    ENRICH_COLUMN_START_STATION_ID + DELIMITER +
    ENRICH_COLUMN_START_EXTERNAL_ID + DELIMITER +
    ENRICH_COLUMN_START_NAME + DELIMITER +
    ENRICH_COLUMN_START_SHORT_NAME + DELIMITER +
    ENRICH_COLUMN_START_LAT + DELIMITER +
    ENRICH_COLUMN_START_LON + DELIMITER +
    ENRICH_COLUMN_START_RENTAL_METHODS0 + DELIMITER +
    ENRICH_COLUMN_START_RENTAL_METHODS1 + DELIMITER +
    ENRICH_COLUMN_START_CAPACITY + DELIMITER +
    ENRICH_COLUMN_START_EIGHTD_HAS_KEY_DISPENSER + DELIMITER +
    ENRICH_COLUMN_START_HAS_KIOSK + DELIMITER +
    ENRICH_COLUMN_START_GOOGLE_API_GEOCODING_JSON + DELIMITER +
    ENRICH_COLUMN_END_DATE + DELIMITER +
    ENRICH_COLUMN_END_STATION_CODE + DELIMITER +
    ENRICH_COLUMN_END_STATION_ID + DELIMITER +
    ENRICH_COLUMN_END_EXTERNAL_ID + DELIMITER +
    ENRICH_COLUMN_END_NAME + DELIMITER +
    ENRICH_COLUMN_END_SHORT_NAME + DELIMITER +
    ENRICH_COLUMN_END_LAT + DELIMITER +
    ENRICH_COLUMN_END_LON + DELIMITER +
    ENRICH_COLUMN_END_RENTAL_METHODS0 + DELIMITER +
    ENRICH_COLUMN_END_RENTAL_METHODS1 + DELIMITER +
    ENRICH_COLUMN_END_CAPACITY + DELIMITER +
    ENRICH_COLUMN_END_EIGHTD_HAS_KEY_DISPENSER + DELIMITER +
    ENRICH_COLUMN_END_HAS_KIOSK + DELIMITER +
    ENRICH_COLUMN_END_GOOGLE_API_GEOCODING_JSON + DELIMITER +
    ENRICH_COLUMN_DURATION_SEC + DELIMITER +
    ENRICH_COLUMN_IS_MEMEMBER

  val ENRICH_START_COLUMNS: Seq[String] = Seq(
    ENRICH_COLUMN_START_DATE,
    ENRICH_COLUMN_START_STATION_CODE,
    ENRICH_COLUMN_START_STATION_ID,
    ENRICH_COLUMN_START_EXTERNAL_ID,
    ENRICH_COLUMN_START_NAME,
    ENRICH_COLUMN_START_SHORT_NAME,
    ENRICH_COLUMN_START_LAT,
    ENRICH_COLUMN_START_LON,
    ENRICH_COLUMN_START_RENTAL_METHODS0,
    ENRICH_COLUMN_START_RENTAL_METHODS1,
    ENRICH_COLUMN_START_CAPACITY,
    ENRICH_COLUMN_START_EIGHTD_HAS_KEY_DISPENSER,
    ENRICH_COLUMN_START_HAS_KIOSK,
    ENRICH_COLUMN_START_GOOGLE_API_GEOCODING_JSON,
    ENRICH_COLUMN_DURATION_SEC,
    ENRICH_COLUMN_IS_MEMEMBER
  )

  val ENRICH_END_COLUMNS: Seq[String] = Seq(
    ENRICH_COLUMN_END_DATE,
    ENRICH_COLUMN_END_STATION_CODE,
    ENRICH_COLUMN_END_STATION_ID,
    ENRICH_COLUMN_END_EXTERNAL_ID,
    ENRICH_COLUMN_END_NAME,
    ENRICH_COLUMN_END_SHORT_NAME,
    ENRICH_COLUMN_END_LAT,
    ENRICH_COLUMN_END_LON,
    ENRICH_COLUMN_END_RENTAL_METHODS0,
    ENRICH_COLUMN_END_RENTAL_METHODS1,
    ENRICH_COLUMN_END_CAPACITY,
    ENRICH_COLUMN_END_EIGHTD_HAS_KEY_DISPENSER,
    ENRICH_COLUMN_END_HAS_KIOSK,
    ENRICH_COLUMN_END_GOOGLE_API_GEOCODING_JSON,
    ENRICH_COLUMN_DURATION_SEC,
    ENRICH_COLUMN_IS_MEMEMBER
  )
}
